name: Rust CI workflow

on:
  push:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: run tests
        working-directory: ./src-tauri/
        run: cargo test
