name: Rust CI workflow

on:
  push:
  paths:
    - ./src-tauri/src/test/**

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: tauri deps
        run: |
          sudo apt update && sudo apt install -y \
          libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          webkit2gtk-driver \
          xvfb

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: run tests
        working-directory: ./src-tauri/
        run: cargo test
